<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>Ventaja Designs</title>
	<style type="text/css">
	<!--
	body {background-color:transparent;}
	-->
	</style>
	<LINK REL=stylesheet HREF="style.css" TYPE="text/css">
</head>
<body text="#ffffff">
<font face="Berlin Sans FB Demi"><center>
<h2>Comments/Questions</h2>
<form method="post" action="process.php">
First Name:<br>        
<input name="first_name" size="33"   type="text"     style=" border-color:#ffffff;height:20px;background-color:transparent;color:#ffffff;font-size:12pt; font-family:Berlin Sans FB Demi;border-style:solid;">  <br>   <br>
E-mail:<br>
<input name="email"    size="33"     type="text"     style=" border-color:#ffffff;height:20px;background-color:transparent;color:#ffffff;font-size:12pt; font-family:Berlin Sans FB Demi;border-style:solid;">  <br>   <br>
Comments/Questions:<br>
<textarea name="comments" rows=5 cols=33 style=" border-color:#ffffff;background-color:transparent;color:#ffffff;font-size:12pt; font-family:Berlin Sans FB Demi;border-style:solid;"></textarea><br><br>
<input type="submit" value="Submit" style=" border-color:#ffffff;background-color:transparent;color:#ffffff;font-size:12pt; font-family:Arial;border-style:solid;">
</form>

</body>
</html>
